<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('courses')->insert([
            // [
            //     'name' => 'English for Beginners',
            //     'language' => 'English',
            //     'level' => 'A2',
            //     'group_size' => 10,
            //     'start_date' => '2025-05-01',
            //     'end_date' => '2025-06-01',
            //     'price' => 199.99,
            //     'instructor_id' => 1, 
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Advanced Spanish',
            //     'language' => 'Spanish',
            //     'level' => 'C1',
            //     'group_size' => 12,
            //     'start_date' => '2025-06-15',
            //     'end_date' => '2025-07-15',
            //     'price' => 299.99,
            //     'instructor_id' => 2, 
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            [
                'name' => 'intermediate Spanish',
                'language' => 'Spanish',
                'level' => 'B1',
                'group_size' => 12,
                'start_date' => '2025-06-15',
                'end_date' => '2025-07-15',
                'price' => 299.99,
                'instructor_id' => 2, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Advanced Polish',
                'language' => 'Polish',
                'level' => 'C1',
                'group_size' => 15,
                'start_date' => '2025-07-15',
                'end_date' => '2025-08-15',
                'price' => 399.99,
                'instructor_id' => 2, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'French for Beginners',
                'language' => 'French',
                'level' => 'A2',
                'group_size' => 8,
                'start_date' => '2025-08-01',
                'end_date' => '2025-09-01',
                'price' => 249.99,
                'instructor_id' => 1, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'German for Beginners',
                'language' => 'German',
                'level' => 'A2',
                'group_size' => 15,
                'start_date' => '2025-09-01',
                'end_date' => '2025-10-01',
                'price' => 499.99,
                'instructor_id' => 1, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Italian for Beginners',
                'language' => 'Italian',
                'level' => 'A2',
                'group_size' => 10,
                'start_date' => '2025-10-01',
                'end_date' => '2025-11-01',
                'price' => 199.99,
                'instructor_id' => 1, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Russian for Beginners',
                'language' => 'Russian',
                'level' => 'A1',
                'group_size' => 10,
                'start_date' => '2025-11-01',
                'end_date' => '2025-12-01',
                'price' => 99.99,
                'instructor_id' => 1, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chinese for Beginners',
                'language' => 'Chinese',
                'level' => 'A2',
                'group_size' => 10,
                'start_date' => '2025-12-01',
                'end_date' => '2026-01-01',
                'price' => 899.99,
                'instructor_id' => 1, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Advanced Japanese',
                'language' => 'Japanese',
                'level' => 'B2',
                'group_size' => 8,
                'start_date' => '2026-01-01',
                'end_date' => '2026-02-01',
                'price' => 399.99,
                'instructor_id' => 1, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Arabic for Beginners',
                'language' => 'Arabic',
                'level' => 'A1',
                'group_size' => 10,
                'start_date' => '2026-02-01',
                'end_date' => '2026-03-01',
                'price' => 199.99,
                'instructor_id' => 1, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Portuguese for Beginners',
                'language' => 'Portuguese',
                'level' => 'A2',
                'group_size' => 10,
                'start_date' => '2026-03-01',
                'end_date' => '2026-04-01',
                'price' => 199.99,
                'instructor_id' => 1, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Swedish for Beginners',
                'language' => 'Swedish',
                'level' => 'A2',
                'group_size' => 10,
                'start_date' => '2026-05-01',
                'end_date' => '2026-06-01',
                'price' => 199.99,
                'instructor_id' => 1, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
